name: yolo-detect
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy<2
  - pandas
  - pillow
  - opencv=4.6.0
  - matplotlib
  - tqdm
  - pip
  - pip:
      - ultralytics==8.1.35


